---
title: "p8105_hw2_smi2112"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Problem 1

Read and clean the data:

```{r}
library(tidyverse)
library(dplyr)
transit_data = read_csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>%
  select(line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, entrance_type, ada) %>% 
  mutate(entry = if_else(entry == "YES", TRUE, FALSE))
```

Short paragraph:

... these data are not tidy yet ...........

Number of distinct stations: 465

```{r}
count(distinct(transit_data, line, station_name))
```

Number of ADA compliant stations: 84

```{r}
transit_data %>%
  select(line, station_name, ada) %>% 
  group_by(line, station_name) %>% 
  filter(ada == TRUE) %>% 
  n_distinct()

```

Proportion of station entrances/exits without vending allowed entrace: 0.0980

```{r}
38.7

prop.table(table(transit_data$vending))*100
```

Reformat data:

```{r}
transit_data_tidy = gather(transit_data, key = route_number, value = route_name, route1:route11) %>% 
  mutate(route_number = recode(route_number, 
                               "route1" = 1, 
                               "route2" = 2, 
                               "route3" = 3,
                               "route4" = 4, 
                               "route5" = 5, 
                               "route6" = 6, 
                               "route7" = 7, 
                               "route8" = 8, 
                               "route9" = 9, 
                               "route10" = 10, 
                               "route11" = 11)) 

is.numeric(transit_data_tidy$route_number)
is.character(transit_data_tidy$route_name)
```

Number of distinct stations serving the A train: 60

```{r}
transit_data_tidy %>%
  select(line, station_name, route_name) %>% 
  filter(route_name == "A") %>% 
  n_distinct()
```

Number of distinct stations serving the A train that are ADA compliant: 17

```{r}
transit_data_tidy %>%
  select(line, station_name, route_name, ada) %>% 
  filter(route_name == "A" & ada == TRUE) %>% 
  n_distinct()
```





